### ISSUE TITLE
Broken link to the quickstart guide

### ISSUE THREAD

**Issue by EsmeAioli** [rollingrhinoremix/rollingrhinoremix.github.io#1]
Hey guys, nice work here:) 

Just wanted to point out that your link to the quickstart guide on the main page is broken 

> It is recommended that you read our Quick Start Guide in order to understand and utilise our distribution correctly.

It uses https://rollingrhinoremix.github.io/quick-start not https://rollingrhinoremix.github.io/docs-quickstart/

May want to fix that before the release tomorrow:) 

Good luck!

**Comment by ajstrongdev** [comment]
Fixed!
